# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Syrus registered time')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MapModelGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ini_time', models.DateTimeField(verbose_name='Ini time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=200)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historic.Logs')),
            ],
        ),
        migrations.AddField(
            model_name='mapmodelgeneral',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historic.Truck'),
        ),
    ]
