# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historic', '0002_auto_20160907_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='driver',
            new_name='truck_driver',
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
